// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWnPjCV5hnBQaGzMQB2rIPIkRFiYuDLGk',
    appId: '1:933706090310:web:8e1b01659e851701398747',
    messagingSenderId: '933706090310',
    projectId: 'project-manage-962ac',
    authDomain: 'project-manage-962ac.firebaseapp.com',
    storageBucket: 'project-manage-962ac.firebasestorage.app',
    measurementId: 'G-0LT4MT7WVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFyafjJcb1ySTGwr3d2VkBT_Tb4BU5b8U',
    appId: '1:933706090310:android:b2281ff4087fa356398747',
    messagingSenderId: '933706090310',
    projectId: 'project-manage-962ac',
    storageBucket: 'project-manage-962ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGHj3cKTEn7wjr7uWG9uWUq9y3BDplRo',
    appId: '1:933706090310:ios:11a67613c740e241398747',
    messagingSenderId: '933706090310',
    projectId: 'project-manage-962ac',
    storageBucket: 'project-manage-962ac.firebasestorage.app',
    iosClientId: '933706090310-5cvcjk8508qqfdth331sktn18mgknur7.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectmange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXGHj3cKTEn7wjr7uWG9uWUq9y3BDplRo',
    appId: '1:933706090310:ios:11a67613c740e241398747',
    messagingSenderId: '933706090310',
    projectId: 'project-manage-962ac',
    storageBucket: 'project-manage-962ac.firebasestorage.app',
    iosClientId: '933706090310-5cvcjk8508qqfdth331sktn18mgknur7.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectmange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWnPjCV5hnBQaGzMQB2rIPIkRFiYuDLGk',
    appId: '1:933706090310:web:6078af16dd0d4664398747',
    messagingSenderId: '933706090310',
    projectId: 'project-manage-962ac',
    authDomain: 'project-manage-962ac.firebaseapp.com',
    storageBucket: 'project-manage-962ac.firebasestorage.app',
    measurementId: 'G-SF89M2WWBE',
  );

}